/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary-container": "#4f5161",
        "on-error": "#ffefee",
        "on-tertiary-fixed": "#4f4f2e",
        "tertiary-container": "#fefccf",
        "error": "#b31b25",
        "tertiary-fixed": "#fefccf",
        "primary": "#894853",
        "secondary": "#595a6b",
        "surface-container-high": "#e4e2de",
        "secondary-fixed-dim": "#d3d3e6",
        "on-tertiary": "#f7f5c8",
        "primary-fixed-dim": "#ee9da8",
        "on-primary": "#ffeff0",
        "surface-bright": "#f8f6f2",
        "surface-container-highest": "#deddd8",
        "outline": "#777774",
        "on-primary-container": "#642a34",
        "inverse-primary": "#feaab6",
        "tertiary-fixed-dim": "#efedc1",
        "on-tertiary-container": "#61613e",
        "on-secondary": "#f3f1ff",
        "error-container": "#fb5151",
        "surface": "#f8f6f2",
        "on-primary-fixed": "#491520",
        "surface-variant": "#deddd8",
        "surface-tint": "#894853",
        "on-secondary-fixed-variant": "#595a6b",
        "primary-dim": "#7b3c47",
        "on-surface-variant": "#5b5c59",
        "on-primary-fixed-variant": "#6e323d",
        "on-tertiary-fixed-variant": "#6c6b48",
        "secondary-dim": "#4d4f5f",
        "on-error-container": "#570008",
        "on-surface": "#2e2f2d",
        "surface-container-low": "#f2f1ec",
        "error-dim": "#9f0519",
        "secondary-fixed": "#e1e1f5",
        "inverse-on-surface": "#9e9d99",
        "surface-container": "#e9e8e4",
        "background": "#f8f6f2",
        "tertiary": "#5d5d3b",
        "surface-dim": "#d5d4d0",
        "primary-container": "#feaab6",
        "on-background": "#2e2f2d",
        "primary-fixed": "#feaab6",
        "on-secondary-fixed": "#3d3e4e",
        "secondary-container": "#e1e1f5",
        "outline-variant": "#aeadaa",
        "tertiary-dim": "#515130",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#0e0e0d"
      },
      "fontFamily": {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "serif": ["Noto Serif", "serif"],
        "sans": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
